export const PORTFOLIO = {
  name: "Ashish Soni",
  role: "Product-focused Frontend Engineer",
  tagline: "I build interfaces that feel inevitable.",
  location: "Bangalore, India",
  email: "ashishsoni2002@gmail.com",
  links: {
    github: "https://github.com/ashishsoniii",
    linkedin: "https://www.linkedin.com/in/ashishsoniii/",
    site: "https://www.ashishsoni.tech/",
  },
  oneliner: "Product-focused frontend engineer. TypeScript · React · end-to-end — from user research and Figma to production architecture. Currently at ClearFeed. GSoC '23 @ Tor Project.",
  experience: [
    {
      id: "clearfeed",
      company: "ClearFeed",
      companyUrl: "https://clearfeed.ai",
      context: "B2B customer support automation — Slack-native ticketing, AI agents, and help-desk workflows for enterprise SaaS teams.",
      role: "Member of Technical Staff",
      location: "Bangalore",
      period: "Nov 2024 — Present",
      bullets: [
        "Shipped 100+ features across WebApp, Customer Portal & WebChat — owning end-to-end delivery from PRDs and UI design to production. Contributed 400+ PRs through structured code review.",
        "Cut bundle size 40% via code splitting & lazy loading — improved TTI for 20K+ users.",
        "Built Business Schedule, SLA configuration, billing workflows, and AI agent setup UI — drove upsell across 20+ enterprise accounts. WebChat widget adopted by 50+ companies.",
        "Reduced manual QA effort by 2 hrs/release cycle by implementing Playwright UI automation & smoke suites.",
      ],
      stack: ["React", "TypeScript", "Redux", "Playwright", "GraphQL"],
    },
    {
      id: "gap",
      company: "GAP Inc.",
      companyUrl: "https://gapinc.com",
      context: "Global fashion retail giant — $15B+ annual revenue, 3,000+ stores worldwide across GAP, Banana Republic, and Old Navy.",
      role: "React Developer Intern",
      location: "Hyderabad",
      period: "Jul 2024 — Aug 2024",
      bullets: [
        "Migrated Revenue Dashboard from Oracle ADF to React — dropped load times from 3s to under 800ms, saving 30% in licensing costs.",
        "Built a high-performance data table with live filtering and CSV export using TanStack Query and Ant Design.",
      ],
      stack: ["React", "TanStack Query", "Ant Design"],
    },
    {
      id: "govtech",
      company: "Code for GovTech 24 · MeitY",
      companyUrl: "https://codeforgovtech.in",
      context: "Government-backed open source fellowship — building tools for India's digital public infrastructure, run by the Ministry of Electronics and IT.",
      role: "Full-Stack Open Source Contributor",
      location: "Remote",
      period: "Jun 2024 — Oct 2024",
      bullets: [
        "Built a MERN-stack CMS for iGOT Karmayogi (1M+ users) — non-technical managers update content and themes across portals without code deployments, cutting engineering load by 60%.",
      ],
      stack: ["MongoDB", "Express", "React", "Node"],
    },
    {
      id: "gsoc",
      company: "Google Summer of Code · The Tor Project",
      companyUrl: "https://torproject.org",
      context: "The Tor Project builds free, open-source privacy tools used by millions of journalists, activists, and people in censored regions. GSoC is Google's annual global mentorship program for open source contributors.",
      role: "Open Source Developer",
      location: "Remote",
      period: "Jun 2023 — Sep 2023",
      bullets: [
        "Selected from 40,000+ global applicants. Led the rebuild of a public-facing Tor site using Lektor CMS — reaching millions of users.",
        "Post-launch: 40% increase in engagement, 25% drop in bounce rate over the year.",
      ],
      stack: ["Lektor", "Python", "HTML/CSS"],
    },
    {
      id: "yoglabs",
      company: "YogLabs",
      companyUrl: null,
      context: "Early-stage startup building wellness and health technology products.",
      role: "Frontend Developer (Part-Time)",
      location: "Remote",
      period: "Jan 2023 — Jun 2023",
      bullets: [
        "Enhanced 3 dashboards/sites — fixed 20 critical bugs, shipped 4 new features. Deployed on AWS S3.",
      ],
      stack: ["React", "AWS S3"],
    },
  ],
  projects: [
    {
      id: "clearfeed",
      title: "ClearFeed WebChat Widget",
      year: "2025",
      kind: "Product · Production",
      summary: "100+ features shipped. Draggable chat widget — 50+ companies, 20K+ users.",
      detail: "Designed and built the embeddable WebChat surface — drag to reposition, themeable down to the corner radius, ships under 40KB gzipped. Pluggable AI agent config UI sits on top.",
      tech: ["React", "TypeScript", "Vite", "CSS Modules"],
      github: null,
      live: "https://clearfeed.ai",
      featured: true,
    },
    {
      id: "tor",
      title: "Tor Project Snowflake Site",
      year: "2023",
      kind: "Open Source · GSoC",
      summary: "Rebuilt the public site for Tor's Snowflake — censorship circumvention.",
      detail: "Selected from 40K+ applicants. Migrated to Lektor CMS, redesigned the IA, and shipped it to millions. +40% engagement, −25% bounce.",
      tech: ["Lektor", "Python", "HTML/CSS"],
      github: "https://github.com/torproject/snowflake-webextension",
      live: "https://snowflake.torproject.org",
      featured: true,
    },
    {
      id: "nlf",
      title: "NLF Gym Management",
      year: "2024",
      kind: "Full-Stack · MERN",
      summary: "Platform for 400+ members. Cut paperwork 90%, saved 15 hrs/week.",
      detail: "Razorpay payments, CRON-based renewals & birthday automation, role-based admin, deployed on Azure.",
      tech: ["React", "Node", "MongoDB", "Razorpay", "Azure"],
      github: "https://github.com/ashishsoniii/NLF-GYM",
      live: null,
    },
    {
      id: "rajpolice",
      title: "Rajasthan Police Feedback System",
      year: "2024",
      kind: "Civic · Full-Stack",
      summary: "Citizen portal + admin analytics dashboard for state police.",
      detail: "Two web apps — a citizen portal with Botpress chatbot for feedback & polls, plus an admin dashboard with charts and actionable insights.",
      tech: ["Next.js", "Node", "MongoDB", "Botpress"],
      github: "https://github.com/ashishsoniii/rajasthan-police",
      live: null,
    },
    {
      id: "igot",
      title: "iGOT CMS",
      year: "2024",
      kind: "Open Source · GovTech",
      summary: "Custom CMS for India's iGOT learning platform.",
      detail: "CMS for India's iGOT Karmayogi platform — 1M+ users. Non-technical managers update content and themes without code. Reduced engineering load 60%.",
      tech: ["MERN"],
      github: "https://github.com/ashishsoniii/igot-cms",
      live: null,
    },
  ],
  skills: {
    Frontend: ["React", "Next.js", "TypeScript", "JavaScript", "Redux", "TanStack Query", "Zustand", "TailwindCSS", "AntDesign", "MaterialUI", "GraphQL", "REST"],
    Backend: ["Node.js", "NestJS", "Express", "PostgreSQL", "MongoDB", "MySQL", "Firebase", "Redis"],
    "Tools & Infra": ["Git", "Docker", "AWS", "GCP", "GitHub Actions", "Webpack", "Vite", "Figma", "Playwright", "Storybook"],
  },
  skillMeta: {
    React:        { lvl: 5, yrs: 3.5, cat: "Frontend" },
    "Next.js":    { lvl: 4, yrs: 2,   cat: "Frontend" },
    TypeScript:   { lvl: 5, yrs: 3,   cat: "Frontend" },
    JavaScript:   { lvl: 5, yrs: 4,   cat: "Frontend" },
    Redux:        { lvl: 4, yrs: 2.5, cat: "Frontend" },
    "TanStack Query":{ lvl: 4, yrs: 2,   cat: "Frontend" },
    Zustand:      { lvl: 3, yrs: 1,   cat: "Frontend" },
    TailwindCSS:  { lvl: 5, yrs: 3,   cat: "Frontend" },
    AntDesign:    { lvl: 4, yrs: 2,   cat: "Frontend" },
    MaterialUI:   { lvl: 4, yrs: 2,   cat: "Frontend" },
    GraphQL:      { lvl: 3, yrs: 1.5, cat: "Frontend" },
    REST:         { lvl: 5, yrs: 3,   cat: "Frontend" },
    "Node.js":    { lvl: 4, yrs: 3,   cat: "Backend" },
    NestJS:       { lvl: 3, yrs: 1,   cat: "Backend" },
    Express:      { lvl: 4, yrs: 3,   cat: "Backend" },
    PostgreSQL:   { lvl: 3, yrs: 1.5, cat: "Backend" },
    MongoDB:      { lvl: 4, yrs: 2.5, cat: "Backend" },
    MySQL:        { lvl: 3, yrs: 2,   cat: "Backend" },
    Firebase:     { lvl: 3, yrs: 1.5, cat: "Backend" },
    Redis:        { lvl: 3, yrs: 1,   cat: "Backend" },
    Git:          { lvl: 5, yrs: 4,   cat: "Tools" },
    Docker:       { lvl: 3, yrs: 1.5, cat: "Tools" },
    "AWS":        { lvl: 3, yrs: 2,   cat: "Tools" },
    GCP:          { lvl: 2, yrs: 1,   cat: "Tools" },
    "GitHub Actions": { lvl: 3, yrs: 1.5, cat: "Tools" },
    Webpack:      { lvl: 3, yrs: 2,   cat: "Tools" },
    Vite:         { lvl: 4, yrs: 2,   cat: "Tools" },
    Figma:        { lvl: 4, yrs: 3,   cat: "Tools" },
    Playwright:   { lvl: 4, yrs: 1.5, cat: "Tools" },
    Storybook:    { lvl: 3, yrs: 1.5, cat: "Tools" },
  },
  education: {
    school: "Indian Institute of Information Technology, Kota",
    degree: "B.Tech, Computer Science & Engineering",
    period: "Dec 2021 — Jun 2025",
    gpa: "7.8 CGPA",
  },
  highlights: [
    { v: "100+", k: "Features shipped at ClearFeed" },
    { v: "400+", k: "Pull requests merged" },
    { v: "40K+", k: "GSoC applicants — I was selected" },
    { v: "20K+", k: "Users on widgets I built" },
    { v: "−40%", k: "Bundle size reduction" },
  ],
};
